# Generated by Django 4.1.5 on 2023-02-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="discipline",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="partners",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="prize",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rider",
            name="instagram",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="rider",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="rider",
            name="nationality",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="rider",
            name="photo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="rider",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
