# Generated by Django 4.1.5 on 2023-02-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_event_category_event_city_event_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="rank",
            field=models.IntegerField(default=None),
        ),
    ]
