# Generated by Django 4.1.5 on 2023-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0003_rider_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="rank",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
