# Generated by Django 4.1.5 on 2023-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0004_alter_rider_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="events",
            field=models.ManyToManyField(through="wiki.Participation", to="wiki.event"),
        ),
    ]
