# Generated by Django 4.1.5 on 2023-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0005_rider_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
