# Generated by Django 4.1.5 on 2023-03-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0006_rider_birth_rider_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="points",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="participation",
            name="rank",
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="rider",
            name="rank",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
