# Generated by Django 4.1.6 on 2023-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_participation_points_alter_participation_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='sex',
            field=models.CharField(blank=True, default='Unknown', max_length=10),
        ),
    ]
