# Generated by Django 4.1.5 on 2023-03-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0008_rider_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(default="event_name"),
        ),
        migrations.AddField(
            model_name="rider",
            name="slug",
            field=models.SlugField(default="event_name"),
        ),
    ]
