# Generated by Django 4.1.5 on 2023-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0009_event_slug_rider_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="partners",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
