# Generated by Django 4.1.5 on 2023-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0010_alter_event_partners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="partners",
            field=models.TextField(blank=True),
        ),
    ]
