# Generated by Django 4.1.5 on 2023-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0012_alter_event_name_alter_event_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="prize",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
