name: retrive secrets
run-name: ${{ github.actor }} want secrets 🚀
on:
  workflow_dispatch:

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
    - name: Pass secret to action
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        sed -i "/^SECRET_KEY=.*/c\SECRET_KEY=${{ secrets.SECRET_KEY }}" ridefmb/.env || echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> ridefmb/.env
