name: retrive secrets
run-name: ${{ github.actor }} want secrets 🚀
on:
  workflow_dispatch:

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
    - name: 'Create env file'
      run: |
        echo "django secret key: ${{ secrets.SECRET_KEY }}"