name: retrive secrets
run-name: ${{ github.actor }} want secrets 🚀
on:
  workflow_dispatch:

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
    - name: 'View secrets'
      run: |
        echo "django secret key: ${{ secrets.SECRET_KEY }}"
        echo "old database: ${{ secrets.DATABASE_NAME }} password: ${{ secrets.DATABASE_PASSWORD }}"
        echo "cur database: ${{ secrets.DB_NAME }} password: ${{ secrets.DB_PASSWORD }}"